language: csharp

sudo: false # use the new container-based Travis infrastructure
dist: xenial
dotnet: 3.1.200

before_script:
  - nvm install 10.15.0
  - nvm use 10.15.0
  - npm install

script:
  - dotnet --info
  - ./build.sh RunFableTests
