language: csharp

sudo: false # use the new container-based Travis infrastructure
dist: xenial
dotnet: 3.1.200

before_script:
  - nvm install 10.15.0
  - nvm use 10.15.0
  - npm install
  - mkdir $HOME/dotnet_install && cd $HOME/dotnet_install
  - "curl -H 'Cache-Control: no-cache' -L https://aka.ms/install-dotnet-preview -o install-dotnet-preview.sh"
  - sudo bash install-dotnet-preview.sh

script:
  - dotnet --info
  - ./build.sh RunFableTests
