// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsToolkit.ErrorHandling.JobResult")>]
[<assembly: AssemblyProductAttribute("FsToolkit.ErrorHandling")>]
[<assembly: AssemblyDescriptionAttribute("FsToolkit.ErrorHandling is a utility library to work with the Result type in F#, and allows you to do clear, simple and powerful error handling.")>]
[<assembly: AssemblyVersionAttribute("3.2.0")>]
[<assembly: AssemblyFileVersionAttribute("3.2.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsToolkit.ErrorHandling.JobResult"
    let [<Literal>] AssemblyProduct = "FsToolkit.ErrorHandling"
    let [<Literal>] AssemblyDescription = "FsToolkit.ErrorHandling is a utility library to work with the Result type in F#, and allows you to do clear, simple and powerful error handling."
    let [<Literal>] AssemblyVersion = "3.2.0"
    let [<Literal>] AssemblyFileVersion = "3.2.0"
    let [<Literal>] AssemblyConfiguration = "Release"
