// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsToolkit.ErrorHandling.JobResult")>]
[<assembly: AssemblyProductAttribute("FsToolkit.ErrorHandling")>]
[<assembly: AssemblyDescriptionAttribute("An opinionated error handling library for F#")>]
[<assembly: AssemblyVersionAttribute("1.2.6")>]
[<assembly: AssemblyFileVersionAttribute("1.2.6")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsToolkit.ErrorHandling.JobResult"
    let [<Literal>] AssemblyProduct = "FsToolkit.ErrorHandling"
    let [<Literal>] AssemblyDescription = "An opinionated error handling library for F#"
    let [<Literal>] AssemblyVersion = "1.2.6"
    let [<Literal>] AssemblyFileVersion = "1.2.6"
    let [<Literal>] AssemblyConfiguration = "Release"
