// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsToolkit.ErrorHandling.AsyncSeq.Tests")>]
[<assembly: AssemblyProductAttribute("FsToolkit.ErrorHandling")>]
[<assembly: AssemblyDescriptionAttribute("FsToolkit.ErrorHandling is a utility library to work with the Result type in F#, and allows you to do clear, simple and powerful error handling.")>]
[<assembly: AssemblyVersionAttribute("4.2.1")>]
[<assembly: AssemblyFileVersionAttribute("4.2.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsToolkit.ErrorHandling.AsyncSeq.Tests"
    let [<Literal>] AssemblyProduct = "FsToolkit.ErrorHandling"
    let [<Literal>] AssemblyDescription = "FsToolkit.ErrorHandling is a utility library to work with the Result type in F#, and allows you to do clear, simple and powerful error handling."
    let [<Literal>] AssemblyVersion = "4.2.1"
    let [<Literal>] AssemblyFileVersion = "4.2.1"
    let [<Literal>] AssemblyConfiguration = "Release"
