// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsToolkit.ErrorHandling")>]
[<assembly: AssemblyProductAttribute("FsToolkit.ErrorHandling")>]
[<assembly: AssemblyDescriptionAttribute("An opinionated error handling library for F#")>]
[<assembly: AssemblyVersionAttribute("0.0.13")>]
[<assembly: AssemblyFileVersionAttribute("0.0.13")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsToolkit.ErrorHandling"
    let [<Literal>] AssemblyProduct = "FsToolkit.ErrorHandling"
    let [<Literal>] AssemblyDescription = "An opinionated error handling library for F#"
    let [<Literal>] AssemblyVersion = "0.0.13"
    let [<Literal>] AssemblyFileVersion = "0.0.13"
    let [<Literal>] AssemblyConfiguration = "Release"
