<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
        <NoWarn>$(NoWarn); FS3511</NoWarn>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <!-- Error FS3261 : Nullness warning: The types 'System.IAsyncDisposable' and 'System.IAsyncDisposable | null' do not have compatible nullability. -->
        <NoWarn>$(NoWarn); FS3261</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="SampleDomain.fs" />
        <Compile Include="TestData.fs" />
        <Compile Include="../FsToolkit.ErrorHandling.Tests/Expect.fs" />
        <Compile Include="../FsToolkit.ErrorHandling.Tests/Expecto.fs" />
        <Compile Include="../FsToolkit.ErrorHandling.Tests/TestHelpers.fs" />
        <Compile Include="CancellableTaskResultCE.fs" />
        <Compile Include="CancellableTaskValidationCE.fs" />
        <Compile Include="CancellableTaskOptionCE.fs" />
        <Compile Include="ValueTaskValueOptionCE.fs" />
        <Compile Include="CancellableValueTaskResultCE.fs" />
        <Compile Include="CancellableValueTaskOptionCE.fs" />
        <Compile Include="Main.fs" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\FsToolkit.ErrorHandling.IcedTasks\FsToolkit.ErrorHandling.IcedTasks.fsproj" />
    </ItemGroup>
</Project>
